
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AccountPage = lazy(() => import("./pages/AccountPage.tsx"));
const AdminDashboard = lazy(() => import("./pages/AdminDashboard.tsx"));
const AdminPage = lazy(() => import("./pages/AdminPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const AuthCallbackPage = lazy(() => import("./pages/AuthCallbackPage.tsx"));
const ChartTestPage = lazy(() => import("./pages/ChartTestPage.tsx"));
const DeviceAnalyticsPage = lazy(() => import("./pages/DeviceAnalyticsPage.tsx"));
const HowItWorksPage = lazy(() => import("./pages/HowItWorksPage.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const MunyIQPage = lazy(() => import("./pages/MunyIQPage.tsx"));
const PaymentCancelPage = lazy(() => import("./pages/PaymentCancelPage.tsx"));
const PaymentSuccessPage = lazy(() => import("./pages/PaymentSuccessPage.tsx"));
const PredictionGamePage = lazy(() => import("./pages/PredictionGamePage.tsx"));
const PrivacyPolicyPage = lazy(() => import("./pages/PrivacyPolicyPage.tsx"));
const ResultsPage = lazy(() => import("./pages/ResultsPage.tsx"));
const ShoppingCartPage = lazy(() => import("./pages/ShoppingCartPage.tsx"));
const SignupPage = lazy(() => import("./pages/SignupPage.tsx"));
const TermsOfServicePage = lazy(() => import("./pages/TermsOfServicePage.tsx"));
const TestPage = lazy(() => import("./pages/TestPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/account-page", element: <AccountPage />},
	{ path: "/accountpage", element: <AccountPage />},
	{ path: "/admin-dashboard", element: <AdminDashboard />},
	{ path: "/admindashboard", element: <AdminDashboard />},
	{ path: "/admin-page", element: <AdminPage />},
	{ path: "/adminpage", element: <AdminPage />},
	{ path: "/", element: <App />},
	{ path: "/auth-callback-page", element: <AuthCallbackPage />},
	{ path: "/authcallbackpage", element: <AuthCallbackPage />},
	{ path: "/chart-test-page", element: <ChartTestPage />},
	{ path: "/charttestpage", element: <ChartTestPage />},
	{ path: "/device-analytics-page", element: <DeviceAnalyticsPage />},
	{ path: "/deviceanalyticspage", element: <DeviceAnalyticsPage />},
	{ path: "/how-it-works-page", element: <HowItWorksPage />},
	{ path: "/howitworkspage", element: <HowItWorksPage />},
	{ path: "/login-page", element: <LoginPage />},
	{ path: "/loginpage", element: <LoginPage />},
	{ path: "/muny-iq-page", element: <MunyIQPage />},
	{ path: "/munyiqpage", element: <MunyIQPage />},
	{ path: "/payment-cancel-page", element: <PaymentCancelPage />},
	{ path: "/paymentcancelpage", element: <PaymentCancelPage />},
	{ path: "/payment-success-page", element: <PaymentSuccessPage />},
	{ path: "/paymentsuccesspage", element: <PaymentSuccessPage />},
	{ path: "/prediction-game-page", element: <PredictionGamePage />},
	{ path: "/predictiongamepage", element: <PredictionGamePage />},
	{ path: "/privacy-policy-page", element: <PrivacyPolicyPage />},
	{ path: "/privacypolicypage", element: <PrivacyPolicyPage />},
	{ path: "/results-page", element: <ResultsPage />},
	{ path: "/resultspage", element: <ResultsPage />},
	{ path: "/shopping-cart-page", element: <ShoppingCartPage />},
	{ path: "/shoppingcartpage", element: <ShoppingCartPage />},
	{ path: "/signup-page", element: <SignupPage />},
	{ path: "/signuppage", element: <SignupPage />},
	{ path: "/terms-of-service-page", element: <TermsOfServicePage />},
	{ path: "/termsofservicepage", element: <TermsOfServicePage />},
	{ path: "/test-page", element: <TestPage />},
	{ path: "/testpage", element: <TestPage />},

];
